version: 2.1.0.{build}
branches:
  only:
  - master
  - build-fix
os: Visual Studio 2015 RC
configuration: Release
platform:
- x86
- x64
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
install:
- ps: >-
    $env:Path = "C:\Program Files (x86)\MSBuild\14.0\Bin;" + $env:Path
    
    nuget restore .\NETMapnik.sln
    
    git clone -q https://github.com/mapbox/mapnik-vector-tile .\lib\mapnik-vector-tile
    
    git --git-dir=.\lib\mapnik-vector-tile\.git --work-tree=.\lib\mapnik-vector-tile checkout -q tags/v0.8.0
    
    (New-Object Net.WebClient).DownloadFile("https://mapnik.s3.amazonaws.com/dist/dev/vs2015rc1/mapnik-win-sdk-14.0-$env:Platform-v3.0.0-rc1-1158-g73dbec3.7z", "$pwd\mapnik-win-sdk.7z")
    
    7z x .\mapnik-win-sdk.7z -o".\lib\$env:Platform" | FIND /V "ing  "
    
    git apply --directory=$Env:VS140COMNTOOLS\..\..\VC\Include .\lib\mutex.patch 2> $null
    
    git apply --directory=$Env:VS140COMNTOOLS\..\..\VC\Include .\lib\thread.patch 2> $null
test_script:
- ps: vstest.console /Platform:$env:Platform /InIsolation /logger:Appveyor ".\NETMapnik.Test\bin\$env:Platform\$env:Configuration\NETMapnik.Test.dll"
on_success:
- ps: |
    $id = "mapnik" + $(if ($env:Platform -eq "x64") {".x64"})
    $version = $env:APPVEYOR_BUILD_VERSION.Split(".")
    if ($env:APPVEYOR_REPO_TAG -eq $true)
    {
        $version = $version[0] + "." + $version[1] + "." + $version[2]
    }
    else
    {
       $version = $version[0] + "." + $version[1] + "." + $version[2] + "-pre" + $version[3].PadLeft(5,'0')
    }
    nuget pack .\$id.nuspec -NonInteractive -Version $version -Properties id=$id
    Get-ChildItem .\*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
